#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          mysql
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $network $named $time
# Should-Stop:       $network $named $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the mysql database server daemon
# Description:       Controls the main MariaDB database server daemon "mysqld"
#                    and its wrapper script "mysqld_safe".
### END INIT INFO
#
set -e
set -u
SELF=$(cd $(dirname $0); pwd -P)/$(basename $0)
. /lib/lsb/init-functions
${DEBIAN_SCRIPT_DEBUG:+ set -v -x}
test -x /root/cloud_sql_proxy || exit 0
#
# main()
#
case "${1:-''}" in
  'start')
  # Start daemon
  log_daemon_msg "Starting cloudsql proxy" "mysqld"
    # Start proxy
    cd /root/
    ./cloud_sql_proxy -instances=[CONNSTRING]=tcp:[PORT] -credential_file=[credential file] &
  ;;
  'stop')
  # stop proxy
  log_daemon_msg "Stopping cloudsql proxy" "mysqld"
    killall -9 cloud_sql_proxy
  ;;
  *)
  echo "Usage: $SELF start|stop"
  exit 1
  ;;
esac
